name: Docker Container Build
run-name: ${{ github.actor }} triggered docker build
on: [push]
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Save Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: false
          tags: my-image:latest

      - name: save image to tar
        run: |
          docker save -o ~/test.tar myimage:latest

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          docker images -a

      - run: echo "Job's status is ${{ job.status }}."

